### ISSUE TITLE
Solicitud de cooperación

### ISSUE THREAD

**Issue by SHIG-ops** [vixark/SimpleOps#1]
Hola que tal,

Estamos trabajando en la implementación de la factura electrónica para un cliente colombiano y necesitamos ayuda para conectarnos con las autoridades fiscales colombianas (DIAN), te contacto porque veo que ya tienes experiencia en este tipo de implementaciones.
En este momento, nuestro equipo de desarrollo está trabajando en la solución, pero necesitamos a alguien que pueda ayudarnos a conectarnos con la DIAN  proporcionando información local específica. Esto tomaría aproximadamente 3-4 horas de tu tiempo por semana, dependiendo de la fase de integración. Por supuesto, ofrecemos pagar el tiempo que trabajes para realizar este proyecto.

Por favor avísame si estas interesado, para organizar una reunión. 
Gracias y un saludo,
Sergio

**Comment by vixark** [comment]
Hola Sergio, 

En el momento no tengo tiempo disponible para asesorías sobre desarrollos diferentes de SimpleOps.

SimpleOps actualmente puede ser usado para realizar una integración por medio de archivos de texto con programas terceros. Recuerda que SimpleOps está bajo una licencia AGPL-3.0 License por lo que debe ser compartido a tu cliente con el código completo de SimpleOps. Si esta condición te parece aceptable te puedo guiar para realizar la integración con tu programa con SimpleOps para que tu programa pueda generar facturas electrónicas sin ningún costo.

Saludos

David

**Comment by luisgab24** [comment]
Hola Sergio buenas tardes, me interesa lo que me comentas, quedo atento a
tu respuesta para coordinar la reunión, feliz tarde

**Comment by elmegarc** [comment]
Buena tarde, quiero integrar SimpleOps  con unicentaOPOS, logre que se aprobara el software propio con SimpleOps  pero no logro hacer seguimiento a las facturas que genera.

De antemano es una gran herramienta la que creaste. Gracias
