### ISSUE TITLE
Decimales en el json

### ISSUE THREAD

**Issue by elmegarc** [vixark/SimpleOps#5]
Hola vixark espero te encuentres bien, tu herramienta a sido de gran ayuda, tengo un inconveniente cuando pongo decimales en el json el archivo da error "The JSON value could not be converted to System.Int32. Path: $.Líneas[0].Cantidad | LineNumber: 0 | BytePositionInLine: 688." intento trabajar con productos pesados, ejemplo 0.580.

Agradezco de antemano tu colabarocion y aprecio el tiempo que dedicas en atender mi necesidad.

**Comment by vixark** [comment]
Hola, Solo pueden ser números enteros en este campo. Esto es una restricción de la especificación de la DIAN:

![image](https://user-images.githubusercontent.com/68766864/222974725-c6c58d7e-5ea5-4739-ade8-82f63608799b.png)

La alternativa que tienes es que si estabas vendiendo 0,580 de un producto por tonelada, no lo vendas por tonelada sino por kg. Entonces podrías poner 580 kg.
