### ISSUE TITLE
Otros Cargos o AllowanceCharge 

### ISSUE THREAD

**Issue by elmegarc** [vixark/SimpleOps#6]
Buena Tarde, como puedo enviar un cargo adicional en el json de integracion, o que AllowanceCharge vaya true, que no sea descuento si no un cargo mas?, por ejemplo una propina, dices que el c# es mejor no tocarlo por eso acudo a ti, gracias por tu tiempo.

**Comment by vixark** [comment]
Hola, acabo de hacer un pequeño cambio para soportar DescuentoCondicionado y DescuentoComercial desde el JSON.  El descuento condicionado se puede usar para agregar cargos si usas un signo negativo, así:

{
"OrdenCompraN\u00FAmero": "OC222",
"Raz\u00F3n": "Otra",
"VentaPrefijo": null,
"VentaN\u00FAmero": null,
"DescuentoCondicionado": -1500,
"DescuentoComercial": 0,
...

Por el momento no quiero añadir los cargos directamente en el JSON porque implica otras cosas hacia arriba del código, entonces es una solución un poco burda, pero funciona por el momento. 

Tendrás que modificar tu archivo VentaPDF.cshtml para que diga Cargo (o propina según tu caso) en vez de  Descuento cuando detecte que el descuento es negativo.

Saludos

**Comment by elmegarc** [comment]
vale lo probare, muchas gracias, feliz tarde

**Comment by elmegarc** [comment]
Pues lo he probado,  si mando valor negativo la dian me lo rechaza.
![error1](https://github.com/vixark/SimpleOps/assets/36210235/01bf964c-88ae-4396-a39c-a8a5b747df9b)
no se genera el pdf si lo envio positivo lo toma como un descuento
![erro+](https://github.com/vixark/SimpleOps/assets/36210235/87d92577-6098-452a-999c-b236a5405481)

**Comment by vixark** [comment]
Qué raro, justo escribí código para evitar ese error. Intenta sincronizar nuevamente el código. Acabo de volver a subir los cambios.

Si no te funciona, compárteme el JSON que estás usando y yo reviso si tampoco funciona en mi equipo.

**Comment by elmegarc** [comment]
![ok](https://github.com/vixark/SimpleOps/assets/36210235/222b165e-2378-4d82-aa7b-87194fc87254)
Perfecto!!! Feliz Noche
