### ISSUE TITLE
Nota Debito

### ISSUE THREAD

**Issue by JEGG1977** [vixark/SimpleOps#8]
Buenas tardes David.
Continuo con la adaptacion de SimplOps y todo va muy bien. el error 500 parece ser que era del servidor de la DIAN porque pasadas unas horas ya no volvio a salir.

Otro detalle que solucioné fue que el .json presentaba unos errores. y despues de mucho analizarlo, era un problema del formato del archivo que debe ser UTF-8 y mi aplicacion lo generaba ANSI.

para la nota credito que mas se debe colocar en el .json, aparte de los 2 campos:
 "VentaPrefijo": null,
"VentaN\u00FAmero": null,

tienes algun ejemplo del .json para una nota credito?

Muchas gracias por este gran trabajo y ayuda.

**Comment by JEGG1977** [comment]
una cosa mas, en las pruebas simpleOps genera las Nota credito con el mismo consecutivo de la Factura electronica, pero segun me informaron de contabilidad deberia ser otro consecutivo. como lo manejan uds?

**Comment by JEGG1977** [comment]
Avance: Se genero correctamente la Nota credito colocando los valores especificados. pero el .json  debe iniciar con las letas NC.

**Comment by vixark** [comment]
Hola, que bueno que el error era temporal y que ya todo está funcionando bien.

Gracias por el dato de que debe ser UTF-8, lo aclararé en la guía.

No necesitas poner nada más adicional de VentaPrefijo y VentaN\u00FAmero para las notas crédito. Incluso creo que son opcionales, pero no estoy seguro.

Sí tienes razón, se me olvidó especificar en la guía que para nota crédito y nota débito debe iniciar con diferente texto el JSON, estos son:

"VT-" Venta
"NC-" NotaCrédito
"ND-" NotaDébito

El consecutivo de la factura debe ser uno diferente de las facturas por orden contable, pero curiosamente el servidor de la DIAN no controla la numeración de la nota crédito, entonces permite que se envíen números de notas crédito saltadas o incluso repetidas. Pero recomiendo mejor manejar un consecutivo estricto porque no sería raro que en un futuro el servidor de la DIAN empezara a verificar esto y devolver error por ejemplo si se envía una nota crédito con número repetido.

**Comment by elmegarc** [comment]
En relación a las notas tanto de crédito como de débito, es importante tener en cuenta que el consecutivo no requiere una resolución externa, siendo por lo tanto un consecutivo interno. En cuanto al archivo JSON, simplemente necesitamos completar dos valores específicos: "VentaPrefijo": null y "VentaNúmero": null, con la información del documento al cual se le va a aplicar la nota. Posteriormente, se debe proporcionar el consecutivo y el prefijo de la nota, como por ejemplo "Número": 7 y "Prefijo": "NC". Para la integración, se requiere extraer los datos del JSON generado para la factura en una vista, y a partir de ellos, generar el JSON correspondiente para la nota de crédito o débito. Espero haber sido de ayuda
