### ISSUE TITLE
Notificaciones en Validacion de la DIAN

### ISSUE THREAD

**Issue by JEGG1977** [vixark/SimpleOps#9]
Buenas  tardes.
esta  semana revisando en la pagina de la DIAN con el QR encuentro que aunque la factura se ha emitido correctamente y esta en la pagina de la DIAN, en las validaciones del Documento dice lo siguiente:
"NIT o documento de identificacion del emisor debe corresponder al informado en el RUT y debe coincidir con la Razon Social o Nombre comercial registrado"  (2 veces)
"Valida informacion registro RUT" (2 veces)
anteriormenete no salia, y se ha verificado el RUT y Razon social del emisor y son identicas al RUT. 
Agradezco su ayuda.

Saludos.

![WhatsApp Image 2024-05-07 at 1 06 26 PM](https://github.com/vixark/SimpleOps/assets/161727615/803c6017-d307-4613-b141-9e78a1d80a17)

**Comment by vixark** [comment]
Hola,

Mientras sean notificación no es problema para la validez de las facturas. Estas primeras 3 notificaciones me parece raras, hace unos días no salían. Puede ser algo temporal de la DIAN. Por ejemplo, la 'Valida información registro RUT' es una notificación lleva saliendo hace años y nunca ha sido problema ni lo han implementado como error. En resumen, no me preocuparía mucho por esto mientras no se vuelvan errores que eviten la generación de la factura. 

Saludos

**Comment by JEGG1977** [comment]
Buenos dias. 
Ahora la Nota credito si esta presentando unos errores. 

-----------------------------
Error en respuesta de la DIAN.

Al menos un error es de rechazo.

Código Estado: 99
Descripción Estado: Validación contiene errores en campos mandatorios.
Mensaje Estado: Documento con errores en campos mandatorios.
Clave Documento: 37314c5b126b8705bb4aafb02a6b24ba0cb770c41153e6b413c0d99f178d5405e625a2427260e328fa76c9e177aa3d8a
Nombre Archivo: NC4761-D

Rechazo CAE04: No fue informado el fin del periodo de facturación que modifica esta nota crédito.
Rechazo CAE02: No fue informado el inicio del periodo de facturación que modifica esta nota crédito.
Notificación CBF04: La Descripción informada no se encuentra en la lista.
-------------------
En el Json no enuentro donde se deberia reportar inicio y fin de periodo de facturacion


Muchas gracias

**Comment by vixark** [comment]
Hola, Sí, justo hoy también detecté este problema. Eso es un cambio de esta semana porque la semana pasada se podían hacer notas crédito sin problemas.

Esto dice en el anexo 1.9 de la DIAN:

"Notas tipo 22 se utiliza para notas crédito sin
referencia a una factura, pero deben informar el periodo de tiempo al que se quiere afectar con esta nota."

Pero no me queda claro eso... porque normalmente ese periodo de facturación se refiere es a facturas de servicios públicos que por ejemplo, dicen del 15 de abril al 15 de Mayo.  Pero en el caso de notas crédito para facturas que no son de ese tipo, ¿Qué periódo se debe usar? ¿El periodo del año al que correesponde la factura? ¿El del mes al que corresponde la factura?

Ya hablé con la DIAN, pero en la llamada no me supieron explicar y elevaron el caso. Eso se puede demorar...

Si necesitas esto muy urgente, por el momento creo que puedo solucionar esto de manera rápida poniendole esas fechas del 2024: 1 enero a 31 de diciembre, pero la solución más correcta se haría cuando ellos contesten y expliquen cómo se debe hacer.

**Comment by JEGG1977** [comment]
Buenos dias, como es posible colocar las fechas a la nota crédito?

saludos

**Comment by vixark** [comment]
Hola, acabo de subir unos cambios preliminares del código al repositorio. No estoy seguro que funcionen porque no los he podido probar porque en mi equipo de desarrollo tengo el certificado de firma electrónica desactualizado. Pero podrías intentar probarlo en un equipo de pruebas (no en produccion) a ver si te funciona. Agregué un nuevo valor al json que se llama VentaFechaHora con este formato de fecha:

"VentaFechaHora": "2021-01-26T00:00:00.0000000Z",

Ahí deberás poner la fecha de la factura que fue afectada por esa nota crédito o simplemente una fecha cualquiera del mes contable afectado.

Si no tienes afán, puedes esperar hasta pasado mañana que pueda verificar que estos cambios funcionen.

**Comment by vixark** [comment]
> Buenas tardes. esta semana revisando en la pagina de la DIAN con el QR encuentro que aunque la factura se ha emitido correctamente y esta en la pagina de la DIAN, en las validaciones del Documento dice lo siguiente: "NIT o documento de identificacion del emisor debe corresponder al informado en el RUT y debe coincidir con la Razon Social o Nombre comercial registrado" (2 veces) "Valida informacion registro RUT" (2 veces) anteriormenete no salia, y se ha verificado el RUT y Razon social del emisor y son identicas al RUT. Agradezco su ayuda.
> 
> Saludos.
> 
> ![WhatsApp Image 2024-05-07 at 1 06 26 PM](https://private-user-images.githubusercontent.com/161727615/328629778-803c6017-d307-4613-b141-9e78a1d80a17.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTU2NjMsIm5iZiI6MTcxNTcxNTM2MywicGF0aCI6Ii8xNjE3Mjc2MTUvMzI4NjI5Nzc4LTgwM2M2MDE3LWQzMDctNDYxMy1iMTQxLTllNzhhMWQ4MGExNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTkzNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OThjODMwOWNmZDc2NjYzOTNlMzgxNjY2YTI5YzYzMjdmOGIzZTc2YjRiZmMyYmQ0NmJhY2JjMzA1NGIwYWVlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._6GhGi_Hh7EjTI4ve-0kdSugQUYYeQJ6fH6akosVGq8)

Sobre este tema revisa esta parte de este video: https://youtu.be/fRLKZY_VM8I?t=2393
Ahí informan que ahora se debe poner el nombre de la razón social del emisor de la factura exactamente como está en el RUT.

**Comment by JEGG1977** [comment]
Te agradezco mucho, estare pendiete, por ahora continua el error. Saludos.

**Comment by vixark** [comment]
Hola, ya pude ensayarlo en mi computador de desarrollo y efectivamente tenía un error. Pero ya logré emitir la nota crédito de prueba usando el botón 'Pruebas Internas'. Ensáyalo por favor.

En cuanto a la integración con JSON , también ya me funcionó, aunque por el momento se debe hacer un cambio a este JSON adicional.  En vez de

  "Raz\u00F3n": "Otra",

Deberás poner

  "Raz\u00F3n": "Devoluci\u00F3nParcial",

Esto es porque la DIAN eliminó la opción de usar Otra para la razón de nota crédito. Aún quiero hacer otra modificación para mejorar la lógica de esta parte para que pueda decir mejor "RazónNotaCrédito" y "RazónNotaDébito" que no está implementada en este momento.  Pero el cambio sería nuevamente menor. Te avisaré por aquí mismo. 

Ya te debería funcionar. Me cuentas.

**Comment by JEGG1977** [comment]
Buenas Tardes,
Hice pruebas internas y emite bien las nota crédito, pero en la integración (JSON) me sigue el error
Rechazo CAE04: No fue informado el fin del periodo de facturación que modifica esta nota crédito.
Rechazo CAE02: No fue informado el inicio del periodo de facturación que modifica esta nota crédito.
le coloque las 2 líneas según la indicación:
"Raz\u00F3n": "Devoluci\u00F3nParcial",
"VentaFechaHora": "2021-04-21T20:01:51.320548Z",
tienes un JSON de ejemplo que funcione para verificar si hay algo que me esta faltando.

Muchas gracias,

**Comment by vixark** [comment]
Hola 

Adjunto JSON que me funciona 

[NC-Prueba.json](https://github.com/vixark/SimpleOps/files/15328891/NC-Prueba.json)

**Comment by vixark** [comment]
Le acabo de hacer una actualización medianamente importante al procedimiento de integración. En teoría no habría que cambiar nada del JSON aparte de lo que te mencioné anteriormente sobre que la DIAN no acepta la razón 'Otra'.  La actualización fue para tener soporte para la generación de Notas Débito que estaba roto. Próximamente actualizo la guía porque ahora el valor 'Razón' acepta diferentes valores dependiendo si es nota crédito o débito.

 Yo lo verifiqué que funciona bien, pero me gustaría que lo probaras porque se me pudo pasar algo.

**Comment by vixark** [comment]
Hola, encontré un error en las notas crédito. Estaba quedando con fecha incorrecta de periodo contable de la factura en el XML de la nota crédito. Ya lo corregí en el la última actualización del código. Ya probé extensivamente todo este tema de la nota crédito y creo que ya quedó bien.
